#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

upstream_version=$(ynh_app_upstream_version)

#=================================================
#SETTING MULTIMEDIA DIRECTORY
#=================================================
ynh_script_progression "Setting up Multimedia directory..."

ynh_multimedia_build_main_dir
ynh_multimedia_addaccess $app

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:$app "$install_dir"
chown $app:$app "$install_dir/UMS.sh"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

# Create a dedicated systemd config
ynh_config_add_systemd

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Setting up configuration file.."

#UMS read config file from .config/UMS folder
mkdir -p "/home/yunohost.app/$app/.config/UMS"
ynh_config_add --template="UMS.conf.default" --destination="/home/yunohost.app/$app/.config/UMS/UMS.conf"
ynh_config_add --template="WEB.conf.default" --destination="/home/yunohost.app/$app/.config/UMS/WEB.conf"
ynh_config_add --template="VirtualFolders.conf.default" --destination="/home/yunohost.app/$app/.config/UMS/VirtualFolders.conf"

chown -R $app:$app "/home/yunohost.app/$app/.config"
chmod -R  700 "/home/yunohost.app/$app/.config"

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================
ynh_script_progression "Configuring log rotation..."

#TO BE CHECKED : debug.log file in ~/.config/UMS/

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app --description="A DLNA, UPnP and HTTP(S) Media Server." --log="/var/log/$app/$app.log" --needs_exposed_ports "$port_rend"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
